[2023-04-05 23:56:22] INFO (numexpr.utils/MainThread) Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
[2023-04-05 23:56:22] INFO (numexpr.utils/MainThread) Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2023-04-05 23:56:22] INFO (nni.tuner.tpe/MainThread) Using random seed 669534804
[2023-04-05 23:56:22] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2023-04-06 00:17:30] ERROR (nni.runtime.msg_dispatcher_base/Thread-2) '<=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 108, in command_queue_worker
    self.process_command(command, data)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 154, in process_command
    command_handlers[command](data)
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/nni/runtime/msg_dispatcher.py", line 135, in handle_report_metric_data
    if self.is_created_in_previous_exp(data['parameter_id']):
  File "/root/miniconda3/envs/nni/lib/python3.8/site-packages/nni/recoverable.py", line 47, in is_created_in_previous_exp
    return param_id <= self.recovered_max_param_id
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
[2023-04-06 00:18:07] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2023-04-06 00:18:08] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
